unique_constraints_check.py module loaded
All checks passed!
unique_constraints_check.py module loaded
All checks passed!
2024-09-23 17:10:32,187 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:10:32,188 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:10:33,191 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:10:33,191 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:10:34,193 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:10:34,193 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:10:35,199 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:10:35,199 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:10:36,202 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:10:36,203 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:10:37,205 [ERROR] [no_request_id] gunicorn.error: Can't connect to ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
unique_constraints_check.py module loaded
All checks passed!
2024-09-23 17:11:31,184 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:11:31,184 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:11:32,186 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:11:32,186 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:11:33,188 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:11:33,188 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:11:34,193 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:11:34,193 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:11:35,197 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:11:35,197 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:11:36,200 [ERROR] [no_request_id] gunicorn.error: Can't connect to ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
unique_constraints_check.py module loaded
All checks passed!
unique_constraints_check.py module loaded
All checks passed!
unique_constraints_check.py module loaded
All checks passed!
2024-09-23 17:17:04,719 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:17:04,719 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:17:05,724 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:17:05,724 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:17:06,728 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:17:06,729 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:17:07,732 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:17:07,732 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:17:08,736 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:17:08,737 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:17:09,740 [ERROR] [no_request_id] gunicorn.error: Can't connect to ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
unique_constraints_check.py module loaded
All checks passed!
2024-09-23 17:18:44,958 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:18:44,958 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:18:45,959 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:18:45,959 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:18:46,961 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:18:46,961 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:18:47,966 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:18:47,967 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:18:48,970 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:18:48,970 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:18:49,976 [ERROR] [no_request_id] gunicorn.error: Can't connect to ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
unique_constraints_check.py module loaded
All checks passed!
2024-09-23 17:19:15,268 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:19:15,269 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:19:16,270 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:19:16,270 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:19:17,275 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:19:17,275 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:19:18,279 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:19:18,279 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:19:19,284 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:19:19,285 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:19:20,287 [ERROR] [no_request_id] gunicorn.error: Can't connect to ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
unique_constraints_check.py module loaded
All checks passed!
unique_constraints_check.py module loaded
All checks passed!
2024-09-23 17:21:47,166 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:21:47,166 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:21:48,171 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:21:48,172 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:21:49,178 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:21:49,178 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:21:50,181 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:21:50,182 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:21:51,183 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:21:51,184 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:21:52,188 [ERROR] [no_request_id] gunicorn.error: Can't connect to ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
unique_constraints_check.py module loaded
All checks passed!
2024-09-23 17:22:01,607 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:22:01,607 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:22:02,612 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:22:02,612 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:22:03,616 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:22:03,616 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:22:04,621 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:22:04,622 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:22:05,625 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:22:05,626 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:22:06,631 [ERROR] [no_request_id] gunicorn.error: Can't connect to ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
unique_constraints_check.py module loaded
All checks passed!
unique_constraints_check.py module loaded
All checks passed!
2024-09-23 17:29:00,731 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:29:00,731 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:29:01,737 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:29:01,738 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:29:02,744 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:29:02,745 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:29:03,749 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:29:03,749 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:29:04,755 [ERROR] [no_request_id] gunicorn.error: Connection in use: ('127.0.0.1', 8000) (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
2024-09-23 17:29:04,755 [ERROR] [no_request_id] gunicorn.error: Retrying in 1 second. (/Users/merwanehamadi/Library/Caches/pypoetry/virtualenvs/bluewind-5kHNo6Af-py3.12/lib/python3.12/site-packages/gunicorn/glogging.py:272)
